# This is a config for E2B sandbox template.
# You can use 'template_id' (kdktilyyom02o74ogqvg) or 'template_name (gitwit-vanillajs) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='gitwit-vanillajs')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'gitwit-vanillajs' })

team_id = "34eab90a-97dc-4be5-87e3-a17b6e6e8bc6"
dockerfile = "e2b.Dockerfile"
template_name = "gitwit-vanillajs"
template_id = "kdktilyyom02o74ogqvg"
